<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>HyCADTool.Licensing</RootNamespace>
    <AssemblyName>HyCADTool.Licensing</AssemblyName>
    <LangVersion>8.0</LangVersion>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <Reference Include="System.Management" />
  </ItemGroup>
</Project>
