<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>12</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>HYFEA.Viz</RootNamespace>
    <AssemblyName>HYFEA.Viz</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HYFEA.Core\HYFEA.Core.csproj" />
    <ProjectReference Include="..\..\HyCAD.Geometry\HyCAD.Geometry.csproj" />
  </ItemGroup>

</Project>
