<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AutoCAD.NET" Version="25.1.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Tools\input\" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Autodesk.AutoCAD.Interop.Common">
      <HintPath>..\..\..\Rebuild\MyCad\reference\Autodesk.AutoCAD.Interop.Common.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
