<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>HyCAD.BlenderUI.TestHost</RootNamespace>
    <AssemblyName>HyCAD.BlenderUI.TestHost</AssemblyName>
    <PlatformTarget>x64</PlatformTarget>
    <LangVersion>9.0</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HyCAD.BlenderUI\HyCAD.BlenderUI.csproj" />
  </ItemGroup>

</Project>
